### ISSUE TITLE
Keep plugin and plugin configurations in the same place

### ISSUE THREAD

**Issue by noirchen** [gmarik/Vundle.vim#502]
I like to keep plugins and their configurations at the same place, which in the old vundle is something like this in my vimrc:

set nocompatible 
filetype off
filetype plugin indent on

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Plugin 'gmarik/vundle'

Plugin 'drmikehenry/vim-fontdetect'
let s:has_font=fontdetect#hasFontFamily('Inconsolata for Powerline')

Plugin 'bling/vim-airline'
if s:has_font
    let g:airline_powerline_fonts=1
endif
let g:airline_theme='serene'
let g:airline#extensions#tabline#enabled=1

Plugin 'chriskempson/vim-tomorrow-theme'
colorscheme Tomorrow-Night-Bright
..." other tens of plugins

I think this way I can control my plugins in a more structured way. But in the new Vundle.vim, all the plugin configurations must be placed after call vundle#end(), which makes it difficult to manage the plugin configurations. Is there a way to workaround this? Or I have to stick to the old vundle.

**Comment by av3r4ge** [comment]
@jdevera answered it recently in #559

**Comment by jdevera** [comment]
Thanks @av3r4ge
