### ISSUE TITLE
No such variable: "g:vundle_lazy_load"

### ISSUE THREAD

**Issue by masukomi** [gmarik/Vundle.vim#503]
vundle#end tries to unlet g:vundle_lazy_load

for reasons I can't explain I kept getting

    Error detected while processing function vundle#end:
    line    1:
    E108: No such variable: "g:vundle_lazy_load

whenever I opened a file.

The following fixes it.

    func! vundle#end(...) abort
      if (exists("g:vundle_lazy_load"))
        unlet g:vundle_lazy_load
      endif
      call vundle#config#activate_bundles()
    endf

**Comment by jdevera** [comment]
You should user #end only if you have used #begin, otherwise you are wasting time doing expensive rtp manipulation twice. That said, with recent changes, you no longer need that patch, even you chose you mix #rc and #end, which you shouldn't do anyway.
