### ISSUE TITLE
git-pull: line 11: git-sh-setup: No such file or directory

### ISSUE THREAD

**Issue by Anrock** [gmarik/Vundle.vim#510]
MacOS 10.10, git 2.1.0 from homebrew, MacVim from homebrew, Vundle 0b28e334e65b6628b0a61c412fcb45204a2f2bab

Recently got strange issue: all plugins fails to update after calling PluginUpdate with following error:
````
[2014-08-27 16:57:35] 
[2014-08-27 16:57:35] Plugin gmarik/vundle
[2014-08-27 16:57:35] $ cd '/Users/vladislav/.vim/bundle/vundle' && git pull && git submodule update --init --recursive
[2014-08-27 16:57:35] > /usr/local/Cellar/git/2.1.0/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory
````
I checked dir specified in error and git-sh-setup really doesn't exist. I'm not sure who is responsible for that error - git or vundle. Running 
````
git pull && git submodule update --init --recursive
````
in bundle/Vundle.vim manually works fine, producing "Already up-to-date".

**Comment by jinleileiking** [comment]
@wangyandong-ningxia  right answer

**Comment by jinleileiking** [comment]
/usr/bin/login -f <your user name>

**Comment by KryDos** [comment]
Thank @wangyandong-ningxia so much

**Comment by kyleskrinak** [comment]
I can confirm that wangyandong-ningxia's [fix](https://github.com/gmarik/Vundle.vim/issues/510#issuecomment-66959233) addressed my issue as well.

**Comment by Anrock** [comment]
Hm, i can't reproduce this issue anymore. Plugin update works fine in MacVim now.

**Comment by jdevera** [comment]
See here http://stackoverflow.com/questions/24022582/osx-10-10-yosemite-beta-on-git-pull-git-sh-setup-no-such-file-or-directory

Closing, not a Vundle issue.

**Comment by x-ji** [comment]
@jdevera Unfortunately that's probably not the whole case. I can run git well in my iTerm 2.0 with zsh. However I am still unable to run `PluginInstall` in Vundle without explicitly specifying bash.

**Comment by jdevera** [comment]
iTerm seems to be doing something to work around the issue. That is why it works for you on iTerm.

I think this is a vim bug the same way it was an iTem bug.

You can try in MacVim doing this:

```viml
:cd /path/to/a/git/repo
:!git pull
```

Provided your shell is zsh in vim. You should see the problem too.
