### ISSUE TITLE
Filetype is not working with Scala files after installing the vim-scala plugin

### ISSUE THREAD

**Issue by katcipis** [gmarik/Vundle.vim#521]
Initially I thought the problem was on the vim-scala plugin. But as can be seen on the [open issue](https://github.com/derekwyatt/vim-scala/issues/75) there is the possibility that this problem is actually related to Vundle.

**Comment by ches** [comment]
For at least one user on the vim-scala issue referenced, including `filetype off` before the Vundle initialization solved this ftdetect not working. So it looks like it's an instance of #16. I peeked back at @katcipis's `vimrc` at the date he opened the issue on vim-scala, and indeed it too was missing `filetype off`. I think Vundle can likely deem this issue closed.

**Comment by jdevera** [comment]
Thanks @ches ! much appreciated.
