### ISSUE TITLE
Question: keeping vundle.vim separate from other plugins

### ISSUE THREAD

**Issue by jasonkarns** [gmarik/Vundle.vim#538]
I've been working to get my vim configuration to follow the XDG base directory spec. Put simply, my vim configuration directory (with vimrc, and bundle/vundle.vim) will be in `$XDG_CONFIG_HOME/vim`. I would *prefer* to keep the vundle-managed plugins under a different directory `$XDG_DATA_HOME/vim/bundle`. (I'm mostly following this setup: https://tlvince.com/vim-respect-xdg)

My question is regarding how vundle manages itself. My vundle file adds vundle to the runtime path:
`set rtp+=$XDG_CONFIG_HOME/vim/bundle/vundle.vim`. Then I kickoff vundle with a custom location: `call vundle#begin("$XDG_DATA_HOME/vim/bundle")`. But then, as required, I add `Bundle 'gmarik/vundle.vim'`, I end up with two copies of vundle. The first is the 'bootstrapped' (manually git-cloned) copy under CONFIG_HOME, and the other is the vundle-managed copy installed by vundle itself under DATA_HOME.

I realize this is a rather weird set up, but I'm wondering if there is any special incantation that would allow me to tell vundle to manage itself in a different directory than all the other plugins. That way vundle can manage the CONFIG_HOME vundle, and DATA_HOME only contains vundle-installed plugins (not including vundle itself).

Does any of this make sense?

**Comment by jdevera** [comment]
This is not possible. Vundle treats Vundle as any other plugin, so there is not way to put some plugins in one place and some plugins in another place.

You have two options:

 - Do what Vundle does, and treat Vundle as data, not config, the only difference is that you need to bootstrap it, but from then on, it's just another plugin. So you'd just put it in your $XDG_DATA_HOME
 - Go the other extreme, stop treating Vundle as data all together, and remove the line `Bundle gmarik/Vundle.vim` from your vimrc. This line is not compulsory, but its absence means you will get no Vundle updates automatically. Then, as something not managed by Vundle, you can put it anywhere, like your current $XDG_CONFIG_HOME.
