### ISSUE TITLE
Add a cautionary link to README.md to warn fish shell users

### ISSUE THREAD

**Issue by ankur-gupta** [gmarik/Vundle.vim#548]
I'm new to vim. This is a great package manager and would be the first choice of many vim virgins. 
But I use fish shell which trips up vundle. I spent 2 days trying to fix the problem, installing other package managers and vim distributions before I stumbled on the page that told me about the fishyness. 

Fishmongers are on the rise. It'll be unbelievably helpful if we could add a line to README.md that warns the complications of using fish and links to this page: https://github.com/gmarik/Vundle.vim/wiki#faq4.

**Comment by jdevera** [comment]
See #561 and please let me know if that is enough and I'll merge it.

**Comment by jdevera** [comment]
Although it already said "If you have issues, consult the FAQ", but OK, not worth spending people's life on this :)

**Comment by jdevera** [comment]
Done

**Comment by ankur-gupta** [comment]
Thanks, this should be enough to let fish users know that they're not in the same boat as bash users and that they should read the FAQ.
