### ISSUE TITLE
Update only a single plugin

### ISSUE THREAD

**Issue by cyboflash** [gmarik/Vundle.vim#549]
I needed to update a single plugin (i.e. not all of them) but was not able to find a command for it. Is there one? If there isn't can someone point it out and if not then this could be considered a feature request. 

Thanks.

**Comment by lucc** [comment]
Quick and dirty solution: Open a terminal and execute `cd ~/.vim/bundle/the-plugin && git pull`.

**Comment by sagarjauhari** [comment]
@lucc I agree that the above is a quick and dirty solution but I think doing a git-pull on individual plugins defeats the purpose of Vundle. There should be a functionality of PluginUpdate <name of plugin>

**Comment by av3r4ge** [comment]
I also wanted this feature. You can find my fork [here](https://github.com/av3r4ge/Vundle.vim)
If you can test it and say that it works properly, I'll make a pull request.

**Comment by lucc** [comment]
can this be closed in favor of #557?

**Comment by sagarjauhari** [comment]
Yes, can be closed.

**Comment by jdevera** [comment]
Implemented in #557, which is now merged. So please update.
