### ISSUE TITLE
Automatically update plugin by default

### ISSUE THREAD

**Issue by pickfire** [gmarik/Vundle.vim#550]
Set vundle to automatically update plugin by default?

**Comment by lucc** [comment]
This is too unspecific, you have to explain more.

**Comment by Shougo** [comment]
You can add `PlugUpdate!` command in your .vimrc.

**Comment by lucc** [comment]
Can't you just write a cron job to execute `vim +PluginUpdate +q`?

**Comment by lucc** [comment]
As for the "default" in your question: I do not think that such an update policy should be shipped with the default settings of Vundle. I think that updating and installing software is a process the user should initiate manually. But obviously everybody can just use a cron job to get such things done.

**Comment by jdevera** [comment]
Sorry, this is out of Vundle's scope. It would not add any extra value since this can easily be done with well known tools from outside.
