### ISSUE TITLE
E117: unknown function: vundle#installer#list

### ISSUE THREAD

**Issue by lliseil** [gmarik/Vundle.vim#552]
Hi, 
Have trouble making Vundle works with my customized vimrc after shifted my .dotfiles to $XDG (1). But Vundle works with a basic vimrc, so cullprit's in my [ongoing vim config](https://defuse.ca/b/js0uwPCSIWGDxPW2e30VKg). Please is there any particular line to look after in vimrc that is known to cause errors such as:

    :BundleList
    E117: Fonction inconnue : vundle#installer#list
    :BundleSearch <plugin>
    E117: Fonction inconnue : vundle#scripts#all
    :h vundle
    E149: Désolé, aucune aide pour vundle

Station:
- vim v7.4
- Arch linux
- Linux 3.18.1-3-ck x86_64

Uninstalled package `vundle-git 0.9.1.47.g3dcb0c3-1` then installed Vundle from git 
    git clone https://github.com/gmarik/Vundle.vim.git $XDG_CONFIG_HOME/vim/bundle/Vundle.vim

Also did uninstall all *vim* packages as per  (2) then reinstall vim-runtime & vim, then Vundle: same issue.

(1) Working configuration with vim, Vundle and $XDG  https://github.com/gmarik/Vundle.vim/issues/538
(2) https://stackoverflow.com/questions/14697797/cant-get-bundleinstall-working-for-vundle

EDIT: typos

**Comment by lucc** [comment]
(You could also post a minimal vimrc file, yours is quite long.)

Try to use `call vundle#begin(expand('$XDG_CONFIG_HOME').'/vim/bundle')` if you want your bundles in a non standard place.

If this does not help you should post a minimal vimrc, the value of &rtp, the output of :scriptnames or so.

**Comment by BirMa** [comment]
Also make sure you don't ruin vundles runtimepath configuration.
See the line:
```set rtp+=~/.vim/bundle/Vundle.vim```
in your vimrc.
I had a
```set runtimepath=$XDG_CONFIG_HOME/vim,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,$XDG_CONFIG_HOME/vim/after```
in my vimrc afterwards and it obviously trashed everything. I just put it before vundles line and it worked fine.

**Comment by lliseil** [comment]
Thanks BirMa! Yes setting vim's environment *before* the Vundle's conf lines solves this issue.

**Comment by lucc** [comment]
On github you normally do not edit the title to mark a topic as solved but just press the corresponding button instead.  This issue is still listed as an open issue until you press the button.

**Comment by lliseil** [comment]
lucc, got it and sorry for being unattentive on where I was operating.

**Comment by Jero786** [comment]
`Thanks BirMa! Yes setting vim's environment before the Vundle's conf lines solves this issue.`
+1

**Comment by getsadzeg** [comment]
http://stackoverflow.com/a/22398235/4279735

I solved with this.

**Comment by Pinyupen** [comment]
After several  days,i solved this Problem  by move 'runtime! debian.vim' before vundle code.

**Comment by getsadzeg** [comment]
@Pinyupen that's what I commented ~9 months ago.

**Comment by zillani** [comment]
this worked for me! https://askubuntu.com/questions/894118/vundle-installation-fail
