### ISSUE TITLE
Unknown function: vundle#begin~~~~again

### ISSUE THREAD

**Issue by YDSS** [gmarik/Vundle.vim#553]
I'm so confused, and I thought my problem is not like [#506](https://github.com/gmarik/Vundle.vim/issues/506). I have no idea where to check.
Any answer is helpful!

Here is the error:
![error](https://cloud.githubusercontent.com/assets/6086537/5721123/99407ecc-9b68-11e4-99c2-8ea2ecddf338.JPG)

Here is my .vimrc:
```
set nocompatible
syntax on

filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
let path='~/.vim/bundle/Vundle.vim'

call vundle#begin()
" alternatively, pass a path where Vundle should install plugins

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required

set fencs=utf-8,gb18030,gb2312,latin-1
set fenc=utf-8
set enc=utf-8

set nu
set ts=4
set sw=4
set smarttab
set expandtab
set autoindent
set cindent

set foldmethod=marker
set foldmarker={,}
set foldlevel=10

" NERDTree
"map <F7> <Esc>:NERDTreeToggle<CR>
"map <F8> <Esc>:TlistToggle<CR>

"let NERDTreeWinSize=45
```

Here is output of `:scriptnames`
```
~/.jumbo/etc/vimrc
~/.jumbo/share/vim/vimfiles/archlinux.vim
~/.jumbo/share/vim/vim74/vimrc_example.vim
~/.jumbo/share/vim/vim74/syntax/syntax.vim
~/.jumbo/share/vim/vim74/syntax/synload.vim
~/.jumbo/share/vim/vim74/syntax/syncolor.vim
~/.jumbo/share/vim/vim74/filetype.vim
~/.jumbo/share/vim/vim74/ftplugin.vim
~/.jumbo/share/vim/vim74/indent.vim
~/.vimrc
~/.jumbo/share/vim/vim74/syntax/nosyntax.vim
~/.jumbo/share/vim/vim74/ftoff.vim
~/.jumbo/share/vim/vimfiles/autoload/vundle.vim
~/.jumbo/share/vim/vim74/plugin/getscriptPlugin.vim
~/.jumbo/share/vim/vim74/plugin/gzip.vim
~/.jumbo/share/vim/vim74/plugin/matchparen.vim
~/.jumbo/share/vim/vim74/plugin/netrwPlugin.vim
~/.jumbo/share/vim/vim74/plugin/rrhelper.vim
~/.jumbo/share/vim/vim74/plugin/spellfile.vim
~/.jumbo/share/vim/vim74/plugin/tarPlugin.vim
~/.jumbo/share/vim/vim74/plugin/tohtml.vim
~/.jumbo/share/vim/vim74/plugin/vimballPlugin.vim
~/.jumbo/share/vim/vim74/plugin/zipPlugin.vim
~/.jumbo/share/vim/vim74/scripts.vim
~/.jumbo/share/vim/vim74/ftplugin/vim.vim
~/.jumbo/share/vim/vim74/indent/vim.vim
~/.jumbo/share/vim/vim74/syntax/vim.vim
~/.jumbo/share/vim/vim74/syntax/lua.vim
~/.jumbo/share/vim/vim74/syntax/perl.vim
~/.jumbo/share/vim/vim74/syntax/pod.vim
~/.jumbo/share/vim/vim74/syntax/python.vim
```

**Comment by Shougo** [comment]
You should check `~/.vim/bundle/Vundle.vim` directory.
Vundle is installed?

**Comment by YDSS** [comment]
Yes,of course~~~~~~
![pwd](https://cloud.githubusercontent.com/assets/6086537/5732503/dce974a2-9bcd-11e4-95c1-4e7e7622e426.JPG)

**Comment by tomofumikitano** [comment]
Your .vimrc works on my Mac. What OS and vim package are you using?
If you are using pre-installed minimum version of vim, such as vim-tiny on Ubuntu for example, please try uninstall minimum version and reinstall regular version of vim package.

**Comment by YDSS** [comment]
@tomofumikitano I'm not sure if it is a regular version or not.My os is centos~

**Comment by YDSS** [comment]
@tomofumikitano Here is version:

![version](https://cloud.githubusercontent.com/assets/6086537/5733204/3ab9ae9c-9bda-11e4-8b6c-4a0a670623dd.JPG)

**Comment by lucc** [comment]
What does `:echo globpath(&rtp, 'autoload/vundle.vim')` give for you?

**Comment by tomofumikitano** [comment]
When I use CentOS/RedHat, I always install vim-enhanced package. So please try,

``` yum list installed | grep vim``` to list installed vim package 
``` yum install vim-enhanced ``` to install vim-enhanced package

**Comment by YDSS** [comment]
@lucc 
Here is print of `:echo globpath(&rtp, 'autoload/vundle.vim')`
![echo](https://cloud.githubusercontent.com/assets/6086537/5751325/ddaa4e78-9c9c-11e4-8eb1-4d755a4637cb.JPG)

**Comment by YDSS** [comment]
@tomofumikitano 
This vim is not installed by yum but a internal tool of company~

**Comment by YDSS** [comment]
@lucc 
I notice the first path is not used in this enviroment, so I try to hide it and vundle works well now.But I still don't know why~~~

**Comment by lucc** [comment]
We have seen many issues when people have two versions of Vundle in their rtpaths. Don't know why it is a problem either (at least not if both are the same version). Some Vim internal stuff maybe. But I think one can easily live with just one version of Vundle :smile:

**Comment by YDSS** [comment]
@lucc Thanks!Since this issue has been resolved, I think you can close it.

**Comment by lucc** [comment]
As you opened it and I don't have write access to the repository I think you can close it.

**Comment by ryanwinchester** [comment]
I had this problem and recloned Vundle.vim and the problem went away.
