### ISSUE TITLE
can't get vundle work

### ISSUE THREAD

**Issue by MadDooggy** [gmarik/Vundle.vim#554]
When I check the scriptnames, vundle hasn't been loaded.
Then I :source vundle.vim , I get messages like this

Error detected while processing /home/doubi/.vim/bundle/Vundle.vim/autoload/vundle.vim:
line    6:
E492: Not an editor command: ^M
line    9:
E182: Invalid command name
line   10:
E492: Not an editor command: ^M
line   12:
E182: Invalid command name
line   13:
E492: Not an editor command: ^M
line   15:
E182: Invalid command name
line   16:
E492: Not an editor command: ^M
line   18:
E182: Invalid command name
line   19:
E492: Not an editor command: ^M
line   21:
E182: Invalid command name
line   22:
E492: Not an editor command: ^M
line   24:
E182: Invalid command name
line   25:
E492: Not an editor command: ^M
line   28:
E492: Not an editor command: ^M
line   35:
E492: Not an editor command: ^M
line   44:
E492: Not an editor command: ^M
line   46:
E15: Invalid expression: (has('signs'))^M
line   84:
E171: Missing :endif

But I havn't edited it at all.

**Comment by maljub01** [comment]
Looks like the file is using Windows line endings. You should be able to fix this by converting them to unix line endings using `dos2unix`:

```
dos2unix /home/doubi/.vim/bundle/Vundle.vim/autoload/vundle.vim
```

**Comment by jdevera** [comment]
@MadDooggy did you get this solved?

**Comment by jdevera** [comment]
No news, and looks like a non-vundle issue. Feel free to comment if you need more help, or reopen if you still think it's a Vundle thing.

**Comment by juicejuice** [comment]
I had this exact issue on MacVim, you have to update your .gitconfig and disable autocrlf. I had sert autocrlf=true for another project I'm working on.
