### ISSUE TITLE
Smart plugin update

### ISSUE THREAD

**Issue by sagarjauhari** [gmarik/Vundle.vim#556]
Update plugins only if the the timestamp of last commit (for github plugins) has changed. And there can always be 'forceupdate' which mimics the current behavior of updating all the plugins no matter what.

Force update can be used in cases when the plugin author has rebased into the old commits.

**Comment by lucc** [comment]
What is the issue/error/problem you get? How do you get it? *Why must it be fixed?*

What should be changed? Which command needs to work differently, which functions in Vundle need to change?

**Comment by jdevera** [comment]
I also don't understand this request. Doing a `pull` will update only if there are new commits. How do we get *smarter*?

**Comment by sagarjauhari** [comment]
The issue might have been wrongly framed, sorry about that. I found that PluginUpdate is really slow, and assumed that Vundle is force-reinstalling each plugin irrespective of that fact that it has been updated or not.

**Comment by jdevera** [comment]
Unfortunately, the update process is sequential, so yes, it is slow.
