### ISSUE TITLE
PluginClean removes vundle itself

### ISSUE THREAD

**Issue by huahaiy** [gmarik/Vundle.vim#565]
Run PluginClean, get below, which remove Vundle itself. 

" Removing Plugins:                                                                       |
Plugin 'bubblegum'                                                                        |~
Plugin 'vim-eastwood'                                                                     |~
Plugin 'vim-monokai'                                                                      |~
Plugin 'Vundle.vim'

**Comment by jdevera** [comment]
That means you are missing a line in your vimrc that says: `Plugin 'gmarik/Vundle.vim'`

**Comment by huahaiy** [comment]
I have that  line. Otherwise, I won't be able to use PluginClean, right?

**Comment by jdevera** [comment]
Not necessarily. Can you please post your vimrc?

**Comment by huahaiy** [comment]
""""""""""""""""""""vundle""""""""""""""""""""""""""""
set nocompatible               " be iMproved
filetype off                   " required!

if has('win32') || has('win64')
  set rtp+=~/vimfiles/bundle/Vundle.vim
  call vundle#rc('$HOME/vimfiles/bundle/')
else
  " Usual quickstart instructions
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
endif


 " let Vundle manage Vundle
 " required! 
 Plugin 'gmarik/Vundle'

 " My Bundles here:
 "
 " original repos on github
 Plugin 'tpope/vim-sensible'
 Plugin 'tpope/vim-fugitive'
 Plugin 'tpope/vim-surround'
 Plugin 'tpope/vim-classpath'
 Plugin 'tpope/vim-projectionist'
 Plugin 'tpope/vim-dispatch'
 Plugin 'tpope/vim-fireplace'
 Plugin 'guns/vim-clojure-static'
 Plugin 'guns/vim-clojure-highlight'
 Plugin 'ekalinin/Dockerfile.vim'
 Plugin 'kien/ctrlp.vim'
 Plugin 'luochen1990/rainbow'
 Plugin 'davidoc/taskpaper.vim'
 Plugin 'othree/xml.vim'
 Plugin 'ervandew/supertab'
 Plugin 'scrooloose/nerdcommenter'
 Plugin 'scrooloose/syntastic'
 Plugin 'jcf/vim-latex'
 Plugin 'chrisbra/csv.vim'
 Plugin 'jnurmine/Zenburn'
 Plugin 'junegunn/seoul256.vim'
 Plugin 'majutsushi/tagbar'
 Plugin 'bling/vim-airline'
 Plugin 'Shougo/neocomplcache'
 Plugin 'Shougo/neosnippet.vim'
 Plugin 'venantius/vim-cljfmt'
 " vim-scripts repos
 Plugin 'L9'
 Plugin 'paredit.vim'
 Plugin 'JSON.vim'
 Plugin 'matchit.zip'
 Plugin 'Vim-R-plugin'
 Plugin 'xoria256.vim'
 " non github repos
 "Bundle 'git://git.wincent.com/command-t.git'
 " ...

 call vundle#end()
 filetype plugin indent on     " required!
 "
 " Brief help
 " :PluginList          - list configured bundles
 " :PluginInstall(!)    - install(update) bundles
 " :PluginSearch(!) foo - search(or refresh cache first) for foo
 " :PluginClean(!)      - confirm(or auto-approve) removal of unused bundles
 "
 " see :h vundle for more details or wiki for FAQ
 " NOTE: comments after Bundle command are not allowed..

""""""""""""""""""""General""""""""""""""""""""""""""""
syn on

set tabstop=2
set shiftwidth=2
set expandtab 

set autoindent
set smartindent

" folding by syntax
set fdm=syntax

" matching brackets
"set showmatch

" hightlight search
set incsearch
set hlsearch

" show cursor position
set ruler
set cursorline

" show statusline
set statusline=%<%F%h%m%r%h%w%y\ %=\ lin:%l\,%L\ col:%c%V\ %P
set laststatus=2

" get ride of the annoying bell (both sound and flash)
set vb t_vb=

let mapleader=","
let maplocalleader=","

" insert current time
nmap <leader>ct :execute "normal i" . strftime("%x %X (%Z) ")<Esc>
imap <leader>ct <Esc>:execute "normal i" . strftime("%x %X (%Z) ")<Esc>i

" For those with sadly no function keys available, toggle spelling use \s
imap <Leader>s <C-o>:setlocal spell! spelllang=en_gb<CR>
nmap <Leader>s :setlocal spell! spelllang=en_gb<CR>

" paste mode toggle
nmap <Leader>p :set invpaste<CR>

""""""""""""""""""""Color""""""""""""""""""""""""""""
if has('win32') || has('win64')
  set t_Co=16
  set term=win32
  colors zenburn
else 
  set t_Co=256
  set term=xterm-256color
  colors seoul256
  "colors xoria256
endif
" keep the terminal's background color (e.g. stays transparent)
hi Normal ctermbg=NONE
hi NonText ctermbg=NONE

""""""""""""""""""""Clojure""""""""""""""""""""""""""""
let vimclojure#WantNailgun = 1
let vimclojure#HighlightBuiltins = 1
let vimclojure#DynamicHighlighting = 1
let vimclojure#ParenRainbow = 1
let vimclojure#SplitSize = 15

""""""""""""""""""""LaTex""""""""""""""""""""""""""""
" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse latex-suite. Set your grep
" program to alway generate a file-name.
set grepprg=grep\ -nH\ $*

" TIP: if you write your \label's as \label{fig:something}, then if you
" type in \ref{fig: and press <C-n> you will automatically cycle through
" all the figure labels. Very useful!
set iskeyword+=:

" so .tex file will always be recognized as Latex.
let g:tex_flavor = "latex"
let g:Tex_UseMakefile = 0

""""""""""""""""""""newcomplcache""""""""""""""""""""""""""""
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplcache.
let g:neocomplcache_enable_at_startup = 1
" Use smartcase.
let g:neocomplcache_enable_smart_case = 1
" Use camel case completion.
let g:neocomplcache_enable_camel_case_completion = 1
" Use underbar completion.
let g:neocomplcache_enable_underbar_completion = 1
" Set minimum syntax keyword length.
let g:neocomplcache_min_syntax_length = 3

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Rainbow
let g:rainbow_active = 1
let g:rainbow_conf = { 
  \   'ctermfgs': ['lightyellow', 'lightmagenta', 'lightblue', 'lightgreen', 'darkmagenta', 'darkblue', 'darkgreen', 'lightcyan', 'brown', 'lightred', 'darkcyan', 'darkred'],
  \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'deeppink4', 'darkorchid3', 'yellow4', 'red3', 'dodgerblue']
  \}

" support supertab
imap  <silent><expr><tab>  neocomplcache#sources#snippets_complete#expandable() ? "\<plug>(neocomplcache_snippets_expand)" : (pumvisible() ? "\<c-e>" : "\<tab>")
smap  <tab>  <right><plug>(neocomplcache_snippets_jump) 
inoremap <expr><c-e>     neocomplcache#complete_common_string()

""""""""""""""""""""OtherPlugins""""""""""""""""""""""""""""
" stop unknow filtype message by NERDCommentor
let NERDShutUp=1

" filetype
au BufRead,BufNewFile *.clj        setlocal filetype=clojure
au BufRead,BufNewFile *.cljs       setlocal filetype=clojure
au BufRead,BufNewFile *.cljx       setlocal filetype=clojure
au BufRead,BufNewFile Dockerfile   setlocal filetype=Dockerfile

" airline
let g:airline#extensions#whitespace#enabled = 0
let g:airline_powerline_fonts = 1
let g:airline_theme='bubblegum'
let g:airline#extensions#default#section_truncate_width = {
    \ 'b': 79,
    \ 'x': 60,
    \ 'y': 88,
    \ 'z': 45,
    \ }

**Comment by jdevera** [comment]
You hace vundle installed in a directory called Vundle.vim but your plugin line says `Plugin 'Vundle'`.

This name mismatch makes vundle not recognise Vundle.vim as one of its managed plugins.

So change your vimrc to say `Plugin 'Vundle.vim'` and your problem will go away. Next time vundle will want to remove the old Vundle directory. Let it do it.
