### ISSUE TITLE
Can't install Vundle with vim

### ISSUE THREAD

**Issue by jamyy2000** [gmarik/Vundle.vim#569]
My linux version is Ubuntu 12.04.2 LTS ,when I run “vim +PluginInstall +qall” command,I got errors,
I also used version Ubuntu 14.04 to install Voundle,and got the same error.I also add  the line "set shell=/bin/bash" in my .vimrc file ,but still got the error .How to resolve it,Can you help me .Thanks.
The error message is as below:

Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..HasGitRepo:
line    1:
E484: Can't open file /tmp/v9e4yTa/0
Error detected while processing function MaybeRunBranchSwitch..GetThisBranch:
line    1:
E117: Unknown function: fugitive#head
E116: Invalid arguments for function substitute(fugitive#head(), '/', '-', 'g')
E15: Invalid expression: substitute(fugitive#head(), '/', '-', 'g')
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..GetThatBranch..FindGitDirOrRoot:
line    3:
E484: Can't open file /tmp/v9e4yTa/1
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..FindGitDirOrRoot:
line    3:
E484: Can't open file /tmp/v9e4yTa/2
Error detected while processing function MaybeRunBranchSwitch..HasGitRepo:
line    1:
E484: Can't open file /tmp/v9e4yTa/3
Error detected while processing function MaybeRunBranchSwitch..GetThisBranch:
line    1:
E117: Unknown function: fugitive#head
E116: Invalid arguments for function substitute(fugitive#head(), '/', '-', 'g')
E15: Invalid expression: substitute(fugitive#head(), '/', '-', 'g')
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..GetThatBranch..FindGitDirOrRoot:
line    3:
E484: Can't open file /tmp/v9e4yTa/4
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..FindGitDirOrRoot:
line    3:
E484: Can't open file /tmp/v9e4yTa/5
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..HasGitRepo:
line    1:
E484: Can't open file /tmp/v9e4yTa/6
Error detected while processing function MaybeRunBranchSwitch..GetThisBranch:
line    1:
E117: Unknown function: fugitive#head
E116: Invalid arguments for function substitute(fugitive#head(), '/', '-', 'g')
E15: Invalid expression: substitute(fugitive#head(), '/', '-', 'g')
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..GetThatBranch..FindGitDirOrRoot:
line    3:
E484: Can't open file /tmp/v9e4yTa/7
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..FindGitDirOrRoot:
line    3:
E484: Can't open file /tmp/v9e4yTa/8
Cannot execute shell zsh
Error detected while processing function MaybeRunBranchSwitch..HasGitRepo:
line    1:
E484: Can't open file /tmp/v9e4yTa/9
Error detected while processing function MaybeRunBranchSwitch..GetThisBranch:
line    1:
E117: Unknown function: fugitive#head
-- More --

**Comment by jdevera** [comment]
It seems on a first look completely unrelated to vundle, but let's take a look at your vimrc file. Post it please.

**Comment by jamyy2000** [comment]
Sorry,It's my .vimrc file issue,it change the shell to zsh，I remove this line,and it's OK. Thanks.

**Comment by kosich** [comment]
@jamyy2000 close the issue then, plz
