### ISSUE TITLE
Vundle not loading all plugins

### ISSUE THREAD

**Issue by matthewgrossman** [gmarik/Vundle.vim#572]
On my local mac machine, I'm able to :BundleInstall and run everything fine. However, I'm attempting to bring over my .vim/vimrc over to a RedHat linux server and Vundle isn't choosing to see all the repositories listed in my vimrc. Here's what I'm getting:

![screen shot 2015-03-07 at 2 31 03 am](https://cloud.githubusercontent.com/assets/2601844/6539680/3e8886cc-c472-11e4-8c9c-ba4f490d422d.png)

Running :PluginInstall/:BundleInstall on my mac with the above vimrc works totally fine. However, I get this when installing on RedHat:

![screen shot 2015-03-07 at 2 30 39 am](https://cloud.githubusercontent.com/assets/2601844/6539681/463a1598-c472-11e4-9d69-8bdf6cc7a562.png)

It seems to only be seeing those two Plugins. Any idea why this could be happening?

**Comment by Shougo** [comment]
I think the plugins are already installed.

**Comment by Wolfeettel** [comment]
Can you give me a 101

**Comment by matthewgrossman** [comment]
![screen shot 2015-03-07 at 1 42 00 pm](https://cloud.githubusercontent.com/assets/2601844/6541529/c2ca05d4-c4cf-11e4-8300-f04af8c827b6.png)

My bundle folder is only showing those two plugins, and I'm not getting any of the features by the other plugins anyways

**Comment by av3r4ge** [comment]
Do you have other sourced files which contains vundle configurations?
What happens if you open vim with `vim -u NONE -S <Your .vimrc file>`?

**Comment by matthewgrossman** [comment]
Thats exactly what it was, there was another file w/ Vundle configs (an old vimrc symlinked to ~/.vimrc). Thanks for the help, I removed that and everything worked. Thanks!
