### ISSUE TITLE
PluginUpdate:  No Bundles were selected for operation

### ISSUE THREAD

**Issue by dagon666** [gmarik/Vundle.vim#576]
Recently I wanted to updated my plugins. But Vundle seems to fail. I'm running Arch Linux, vim 7.4 (2013 Aug 10, compiled Mar 16 2015 07:51:40). The relevant .vimrc is: 

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'jpalardy/vim-slime'
call vundle#end()            " required

Attempts to perform :PluginUpdate finishes with an error: No Bundles were selected for operation. 

When trying to do :PluginInstall. All I see is:

Plugin ''
Helptags

It seems that Vundle is not able to parse the vimrc and extract the plugin names. I tried replacing the keyword Plugin with Bundle but without any luck unfortunately.

**Comment by av3r4ge** [comment]
Can you please verify no other scripts are sourced containing Vundle information. You can take a look at `:scriptnames` or start your vim with `vim -u NONE -S <your .vimrc file>` to insure only this .vimrc is loaded initially.
If this doesn't solve the issue, please include the output of `:echo g:bundles` and the rest of your .vimrc.

**Comment by jdevera** [comment]
This might sound silly but let's rule it out: are you typing a space after your `PluginUpdate` command?

**Comment by dagon666** [comment]
Hi @av3r4ge . Thanks for getting back to me so quickly. I guess that vundle has been installed globally by my package manager probably as a dependency for some other package. After removing one of the instances everything works as expected again. Thanks.

**Comment by av3r4ge** [comment]
:+1: 
If that's everything, the issue can be closed.

**Comment by dagon666** [comment]
Yes, that's correct. It was a false alarm.
