### ISSUE TITLE
Invalid plugin name: SuperTab-continued.

### ISSUE THREAD

**Issue by cherrot** [gmarik/Vundle.vim#580]
Yes, this [plugin](https://github.com/vim-scripts/SuperTab-continued.) does have an annoying dot as its name ....
So I config it as follows:

        Plugin 'SuperTab-continued.'

then the plugin name couldn't pass through the checking (for reference:  `elseif a:bundle.name !~ '\v^[A-Za-z0-9_-]%(\.?[A-Za-z0-9_-])*$'` )

**Comment by av3r4ge** [comment]
Is there a reason why you have this plugin?
It has only a single README file which says:
>This script has been renamed to SuperTab -- Van Dewoestine.
http://github.com/vim-scripts/SuperTab--Van-Dewoestine

**Comment by jdevera** [comment]
That plugin is empty, we checked before disallowing the trailing dot. Please update to the new name.

**Comment by cherrot** [comment]
Thanks and sorry for bothering. Its my fault :)
