### ISSUE TITLE
Seems some plugin can not be installed if there is DOS return character

### ISSUE THREAD

**Issue by Lizhangz** [gmarik/Vundle.vim#582]
I am using vundle under Linux. The classtree plugin is using a dos return character. It causes the failure when installing.
As vim is used across platform, I hope vundle can address the return character problem. There is simple tool for the task, like dos2unix etc.

**Comment by jdevera** [comment]
It is rather unfortunate indeed that this does not "just work". Vim itself, being well aware of the existence of windows, could simply interpret those characters properly.

However it seems to me that this falls outside of Vundle's scope, as this amounts to essentially modifying the plugin contents.

But there are things you can do. One is to request the author to use Unix new line characters, as these seem to work also for windows. Another is to fork the two and do these conversions yourself. Then you can just use your fork in Vundle.
