### ISSUE TITLE
Undefined variable: g:vundle#bundles

### ISSUE THREAD

**Issue by acgtyrant** [gmarik/Vundle.vim#584]
I executed `BundleUpdate` successfully Just the other day, but I met this error log when I execute `BundleUpdate` today:

	Error detected while processing function vundle#installer#new:
	line    6:
	E121: Undefined variable: g:vundle#bundles
	E116: Invalid arguments for function copy(g:vundle#bundles), 'index(a:000, v:val.name) > -1')
	E116: Invalid arguments for function filter(copy(g:vundle#bundles), 'index(a:000, v:val.name) > -1')
	E15: Invalid expression: filter(copy(g:vundle#bundles), 'index(a:000, v:val.name) > -1')

Here is my [.vimrc](https://github.com/acgtyrant/dotfiles/blob/master/Vim/.vimrc)

**Comment by jdevera** [comment]
You are a victim of the very common double vundle problem :)

See how your vimrc says:
```
set rtp+=~/.vim/bundle/Vundle.vim
```
And the later:
```
Plugin 'gmarik/vundle'
```

You have a stale vundle under `~/.vim/bundle/Vundle.vim` and an updated one under `~/.vim/bundle/vundle`.

So just change the Plugin line to say:

```viml
Plugin 'gmarik/Vundle.vim'
```

Then start vim again, run a `BundleUpdate` and a `BundleClean` and you should be good to go.
