### ISSUE TITLE
PluginUpdate: You are not currently on a branch

### ISSUE THREAD

**Issue by dracorp** [gmarik/Vundle.vim#590]
Hello
While I executing `:PluginUpdate` I get message:
> You are not currently on a branch. Please specify which branch you want to merge with. See git-pull(1) for details.
>   git pull <remote> <branch>

So I changed line in autoload/vundle/installer.vim from 
`\ 'git pull',`
to 
`\ 'git pull origin master',`
and now almost everything is done well besides updateing Vundle plugin of course (because unstaged changes).
Could you look at it?

**Comment by av3r4ge** [comment]
You probably have somehow get into detached-head mode.
You can verify it further with `git status` with an output containing: "HEAD detached at ...".
You most likely want to `git checkout master` in the problematic repository.

**Comment by dracorp** [comment]
Yes, you're right  but why I had detached HEAD in some plugins?
`git co master && git pull` helps me. So far, all right.

**Comment by av3r4ge** [comment]
> why I had detached HEAD in some plugins?

That's a very good question, which unfortunately I have no answer to. Vundle shouldn't get you to that state.

**Comment by dracorp** [comment]
Maybe problem was in that I've migrated from pathogen to Vundle. But I'm sure that in the beginning was without problems during plugins' upgrade.

**Comment by dracorp** [comment]
On another instance of vimfiles everything is good, so I close the issue.
Best regards, Piotr
