### ISSUE TITLE
i want to know how to config the vimrc file if i use vundle both in Windows and Linux

### ISSUE THREAD

**Issue by jiangxincode** [gmarik/Vundle.vim#595]
hi, i want to know how to config the vimrc file if i use vundle both in Windows and Linux. I tried with this, but failed.

" return OS type, eg: windows, or linux, mac, et.st..
 function! MySys()
 if has("win16") || has("win32") || has("win64") || has("win95")
 return "windows"
 elseif has("unix")
 return "linux"
 endif
 endfunction

if MySys() == "windows"
 let $VIMFILES = $HOME.'/vimfiles'
 elseif MySys() == "linux"
 let $VIMFILES = $HOME.'/.vim'
 endif

set nocompatible " be iMproved, required
 filetype off " required

" set the runtime path to include Vundle and initialize
 set rtp+=$VIMFILES.'/bundle/Vundle.vim'
 if MySys() == "windows"
 let path=$VIMFILES.'/bundle'
 call vundle#begin(path)
 elseif MySys() == "linux"
 call vundle#begin(path)
 endif
 " alternatively, pass a path where Vundle should install plugins
 "call vundle#begin('~/some/path/here')

......

The error log like this, of course ignore the encoding.
 ´¦Àí C:\Users\Administrator_vimrc ʱ·¢Éú´íÎó:
µÚ 24 ÐÐ:
 E117: Unknown function: vundle#begin
µÚ 32 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'gmarik/Vundle.vim'
µÚ 42 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'tomasr/molokai'
µÚ 45 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'godlygeek/tabular'
µÚ 46 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'plasticboy/vim-markdown'
µÚ 49 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'vim-scripts/TxtBrowser'
µÚ 52 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'adimit/prolog.vim'
µÚ 55 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'a.vim'
µÚ 67 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'checksyntax'
µÚ 82 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'taglist.vim'
µÚ 87 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'scrooloose/nerdcommenter'
µÚ 90 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'aperezdc/vim-template'
µÚ 93 ÐÐ:
 E492: ²»ÊǱ༭Æ÷µÄÃüÁî: Plugin 'c.vim'
µÚ 96 ÐÐ:
 E117: Unknown function: vundle#end
µÚ 132 ÐÐ:
 E185: Cannot find color scheme 'molokai'

**Comment by Shougo** [comment]
You should check if the Vundle path is exists and it is installed correctly.

**Comment by jiangxincode** [comment]
I am sure the path is ok, because if i write the config like this, it runs well. but you know keep it sync between two os systems is uncomfortable, so i add the if condition, but it doesn't work.

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/vimfiles/bundle/Vundle.vim
let path='~/vimfiles/bundle'
call vundle#begin(path)
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

**Comment by Shougo** [comment]
OH, I get it.  "~" is not expanded automatically in Windows environment.
I think it is commonly reported problem.
You should use like this:

```vim
set rtp+=$HOME/vimfiles/bundle/Vundle.vim
```

**Comment by jiangxincode** [comment]
I GET IT, thanks a lot!

**Comment by Shougo** [comment]
You should close it..
