### ISSUE TITLE
How to mark some plugins as not updatable?

### ISSUE THREAD

**Issue by unclechu** [gmarik/Vundle.vim#598]
I use Vundle as git-submodule, and l need to mark this plugin as not updatable to ignore it when I do BundleUpdate, can I do it with Vundle?

**Comment by davidjb** [comment]
Seems that you can use the ``pinned`` option for your plugin configuration, eg:
```
  Plugin 'gmarick/Vundle.vim', {'pinned': 1}
```
See https://github.com/gmarik/Vundle.vim/blob/master/doc/vundle.txt#L176.

**Comment by unclechu** [comment]
@davidjb thank you, it works for me.
