### ISSUE TITLE
PluginSearch Error

### ISSUE THREAD

**Issue by noscripter** [gmarik/Vundle.vim#599]
![qq20150510-1 2x](https://cloud.githubusercontent.com/assets/1673877/7553276/8ecc1518-f721-11e4-9dd5-bfcade65c87e.png)

**Comment by alxdnlnko** [comment]
+1

**Comment by alexeykv** [comment]
The same issue while trying to search. Can't even catch text log - it disappears and empty search window showed:
![vundle_search](https://cloud.githubusercontent.com/assets/1814126/7796979/782d071c-02ee-11e5-85ae-c6859569d7cc.png)

**Comment by noscripter** [comment]
I came to the solution, simply remove the `.vundle` folder from your `.vim` directory and use `:PluginInstall!` to update/reinstall the vundle plugin. Then use `:VundleSearch` or `:PluginSearch` again and you shall see the result come out smoothly.

thks for this helpful issue posted by @phillipwei , related issues are #535 and #602

**Comment by noscripter** [comment]
update@20150924:

I dived into the vim script and found that the reason is simple, because the command `:PluginSearch` did just about one thing, use curl to download the json file representing the vim plugins in vim-scripts.org, and so the solution is very simple. Just use curl to download the file from vim-scripts.org to the folder `~/.vim/bunlde/.vundle/` and save as `script-names.vim-scripts.org.json`. 

The main logic is as follows(located in `~/.vim/bundle/Vundle.vim/autoload/vundle/scripts.vim`:

![image](https://cloud.githubusercontent.com/assets/1673877/10076599/f3df63ac-630e-11e5-8e31-ce506cdc812d.png)

So the solution is simple:

1.  just remove the file `~/.vim/bundle/.vundle/script-names.vim-scripts.org.json` and try `:PluginSearch` again.

or use curl or wget to get the file(either is ok, pick one as you like), like:

   *   `curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json http://vim-scripts.org/api/scripts.json`
   
   or 

   *  `wget http://vim-scripts.org/api/scripts.json -v -O ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json`

**Comment by fourlincoln10** [comment]
I followed these steps to fix the scripts not found error...and found that the domain vim-scripts.org has expired. Is the file available anywhere else?

**Comment by gmarik** [comment]
it works for me: i can access the website and the json file. 
What am I doing wrong?

**Comment by nfischer** [comment]
The domain is back up now. I haven't tested `:PluginSearch` though

**Comment by fourlincoln10** [comment]
Just tried it. I was able to download the json file using wget as described above. :PluginSearch! works for me now.

**Comment by gmarik** [comment]
@nfischer @fourlincoln10 thanks for the feedback!

**Comment by rally25rs** [comment]
Strangely this curl command that was listed above:

```
curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json http://vim-scripts.org/api/scripts.json
```

downloaded a 0-byte file, which caused `PluginSearch` to continue to fail. I had to manually open a browser to `http://vim-scripts.org/api/scripts.json` and save the content to `~/.vim/bundle/.vundle/script-names.vim-scripts.org.json`

But now it seems to be working.

**Comment by Logan-47** [comment]
I tried every solution that is given above but I am still facing the same issue any help?

**Comment by yungHa** [comment]
> I tried every solution that is given above but I am still facing the same issue any help?

I'm also facing this issue, I wonder if you have any update??

**Comment by Godron629** [comment]
@yungHa It looks like the site that used to serve that JSON file is no longer active. However, it looks like the JSON is simply a [list of package names](https://web.archive.org/web/20180626202615/http://vim-scripts.org:80/api/scripts.json). I am looking into this :coffee:

**Comment by i-cooltea** [comment]
The root of this problem is that PluginSearch queries http://vim-scripts.org, and this site no longer exists. This is because most vim plugin development and distribution occurs via github/gitlab now.

I recommend searching for plugins directly, or searching for plugins on github. This functionality should be considered dead now.


or use curl or wget to get the file(either is ok, pick one as you like), like:

`curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json `

or

`wget https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json -v -O ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json`

**Comment by lifahao** [comment]
there is no .vundle in ~/.vim/bundle instead of Vundle.vim.I change dir to ~/.vim/bundle/Vundle.vim/autoload,there is there files in it.then use "wget http://vim-scripts.org/api/scripts.json" to download this json file .it works.no errors report anymore.

**Comment by EI5JS** [comment]
@i-cooltea ..all evening trying the different fixes for this issue and none worked but i-cooltea has it spot on. The vim-scripts site no longer exists. 

I deleted my current "script-names.vim-scripts.org.json" from the .vundle folder and ran:

curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json

PluginSearch now works a charm. 

Thank you I-cooltea.

**Comment by Artisflowing** [comment]
@EI5JS I had success with your method, even after deleting my .vundle and having it remade by using :PluginInstall I believe. This is a weird little glitch.

**Comment by sreeakshay** [comment]
changing http://vim-scripts.org/api/scripts.json to https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json In .vim/bundle/Vundle.vim/autoload/vundle/scripts.vim fixed problem for me.

**Comment by alpeshjamgade** [comment]
> @i-cooltea ..all evening trying the different fixes for this issue and none worked but i-cooltea has it spot on. The vim-scripts site no longer exists.
> 
> I deleted my current "script-names.vim-scripts.org.json" from the .vundle folder and ran:
> 
> curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json
> 
> PluginSearch now works a charm.
> 
> Thank you I-cooltea.

worked for me. thanks

**Comment by dancingmonkey** [comment]
> > @i-cooltea ..all evening trying the different fixes for this issue and none worked but i-cooltea has it spot on. The vim-scripts site no longer exists.
> > I deleted my current "script-names.vim-scripts.org.json" from the .vundle folder and ran:
> > curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json
> > PluginSearch now works a charm.
> > Thank you I-cooltea.
> 
> worked for me. thanks

Gracie!

**Comment by thomas-amler-idnow** [comment]
> > The root of this problem is that PluginSearch queries http://vim-scripts.org, and this site no longer exists. This is because most vim plugin development and distribution occurs via github/gitlab now.
> > I recommend searching for plugins directly, or searching for plugins on github. This functionality should be considered dead now.
> > or use curl or wget to get the file(either is ok, pick one as you like), like:
> > `curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json `
> > or
> > `wget https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json -v -O ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json`
> 
> after a lot of google search , this particular worked. I'm happy it worked but can anybody explain me how?

Probably the URL in the code here needs to be replaced with another proper one: https://github.com/VundleVim/Vundle.vim/blob/master/autoload/vundle/scripts.vim#L237

**Comment by thomas-amler-idnow** [comment]
> > The root of this problem is that PluginSearch queries http://vim-scripts.org, and this site no longer exists. This is because most vim plugin development and distribution occurs via github/gitlab now.
> > I recommend searching for plugins directly, or searching for plugins on github. This functionality should be considered dead now.
> > or use curl or wget to get the file(either is ok, pick one as you like), like:
> > `curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json `
> > or
> > `wget https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json -v -O ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json`
> 
> after a lot of google search , this particular worked. I'm happy it worked but can anybody explain me how?

Well the original URL is not available anymore. The code here needs to be fixed to point to a new properly downloadable resource: https://github.com/VundleVim/Vundle.vim/blob/master/autoload/vundle/scripts.vim#L237

**Comment by Armadill0** [comment]
> > The root of this problem is that PluginSearch queries http://vim-scripts.org, and this site no longer exists. This is because most vim plugin development and distribution occurs via github/gitlab now.
> > I recommend searching for plugins directly, or searching for plugins on github. This functionality should be considered dead now.
> > or use curl or wget to get the file(either is ok, pick one as you like), like:
> > `curl -v -o ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json `
> > or
> > `wget https://raw.githubusercontent.com/i-cooltea/resource/master/vim-api_scripts.json -v -O ~/.vim/bundle/.vundle/script-names.vim-scripts.org.json`
> 
> after a lot of google search , this particular worked. I'm happy it worked but can anybody explain me how?

Well the original URL is not available anymore. The code here needs to be fixed to point to a new properly downloadable resource: https://github.com/VundleVim/Vundle.vim/blob/master/autoload/vundle/scripts.vim#L237

**Comment by deividaspetraitis** [comment]
Such behaviour creates a lot of confusion for such new users like me. Why this is not resolved yet with so many ( working ) proposed solutions/workarounds?

**Comment by wyonghao** [comment]
> 
> 
> Such behaviour creates a lot of confusion for such new users like me. Why this is not resolved yet with so many ( working ) proposed solutions/workarounds?

I think the VundleVIM is not actively maintained any more.  and the 'http://vim-scripts.org/api/scripts.json' in the search script doesn't exist any more. maybe someone can pick it up and start to maintain it.
