### ISSUE TITLE
PluginSearch Error

### ISSUE THREAD

**Issue by dmaj7** [gmarik/Vundle.vim#602]
I use MacVim(latest version) and in terminal vim aliased "mvim -v" in my .profile.
After adding install script to my .vimrc, everything works fine but PluginSearch.
As two more people uploaded, same error I meet and I have no idea how to solve it. 

Here is my error message
![screen shot 2015-05-15 at 20 06 46 1](https://cloud.githubusercontent.com/assets/284085/7653698/b9eb5c06-fb52-11e4-9291-0305435efa86.png)

I also add my .vimrc for your reference. 
![screen shot 2015-05-15 at 22 37 09 1](https://cloud.githubusercontent.com/assets/284085/7653764/2a9dc038-fb53-11e4-964f-e17535767fc2.png)

Because of many plugins, I fall in love with Vim
and your Vundle, Plugin manager looks very awesome if search function works perfect for me. 
Please help me use your great tool. 

Thanks, 

Kim, Hongsok

**Comment by dmaj7** [comment]
Ah.. Vundle location is "~/.vim/bundle/Vundle.vim/"

**Comment by PVince81** [comment]
I'm getting this too with vim 7.4.712. It used to work, so the problem might be related to the version update.

**Comment by dmaj7** [comment]
PVince81: Thank you for your reply. My mccvim is based on the vim version 7.4.258.
                  I'm keep searching how to fix it and if I find then I will let you know.

**Comment by dmaj7** [comment]
I just setup my macbook from the scratch and reset all things.
I don't know why but anyway, PluginSearch suddenly works!

**Comment by noscripter** [comment]
c this issue and the solution #599

**Comment by greencopper** [comment]
This is still an issue, the solution for #599 isn't working!

I have just installed Vundle today, got all the plugins installed etc., but searching is not working, getting the above error.

I have followed the solution in #599, but the problem persists.
